config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root 'issues#index'
  resources :issues
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/issue.rb
class Issue < ApplicationRecord
  belongs_to :user

  enum state: [:open, :in_progress, :done]

  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :trackable, :validatable

  has_many :issues, dependent: :destroy

  enum role: [:regular, :admin]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_issue, only: [:show, :edit, :update]

  def index
    @issues = policy_scope(Issue)
  end

  def new
    @issue = Issue.new
  end

  def create
    issue_params = params.require(:issue).permit(:title, :description)

    @issue = Issue.new(issue_params)
    @issue.user = current_user

    if @issue.save
      redirect_to root_url, notice: 'Issue was successfully created.'
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    issue_params = params.require(:issue).permit(:state)

    if @issue.update(issue_params)
      redirect_to root_url, notice: 'Issue was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    authorize Issue

    issue = Issue.find(params[:id])
    issue.destroy

    redirect_to root_url, notice: 'Issue was successfully deleted.'
  end

  private

  def find_issue
    @issue = policy_scope(Issue).find(params[:id])
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController

  protected

  def sign_up(resource_name, resource)
  end

  def after_sign_up_path_for(resource)
    new_user_session_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/issues/edit.html.erb
<h1>Edit issue</h1>

<%= form_for @issue do |f| %>
  Title: <%= @issue.title %><br />
  Description: <%= @issue.description %><br />
  State: <%= f.select :state, Issue.states.keys.to_a %><br />

  <%= f.submit %>
<% end %>

<%= link_to 'Back to Issues', root_path %>

app/views/issues/index.html.erb
<%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>

<h1>Issues</h1>

<%= link_to 'New Issue', new_issue_path %><br /><br />

<table>
  <% @issues.each do |issue| %>
    <tr>
      <td><%= link_to issue.title, issue %></td>
      <td><%= issue.description %></td>
      <td><%= issue.state %></td>
      <td><%= link_to 'Edit', edit_issue_path(issue) %></td>

      <% if policy(Issue).destroy? %>
        <td>
          <%= link_to 'Delete', issue_path(issue), method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/issues/new.html.erb
<h1>Create issue</h1>

<%= form_for @issue do |f| %>
  Title: <%= f.text_field :title %>
  <%= @issue.errors[:title].join(',') %><br />

  Description: <%= f.text_area :description %><br />

  <%= f.submit %>
<% end %>

<%= link_to 'Back to Issues', root_path %>

app/views/issues/show.html.erb
<h1><%= @issue.title %></h1>

<%= link_to 'Edit', edit_issue_path(@issue) %>
<% if policy(Issue).destroy? %>
  | <%= link_to 'Delete', issue_path(@issue), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

<p>Description: <%= @issue.description %></p>
<p>State: <%= @issue.state %></p>

<%= link_to 'Back to Issues', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IssueTracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>